{{- if .Values.ingressRoute.enabled -}}
{{- $ingressRoute := .Values.ingressRoute -}}
{{- if $ingressRoute.hosts }}
{{- range $ingressRoute.hosts }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .host | replace "." "-" }}-cert
spec:
  secretName: {{ .host | replace "." "-" }}-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - Dreadnaut Ltd
  commonName: {{ .host }}
  isCA: false
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - {{ .host }}
  issuerRef:
    name: {{ $ingressRoute.clusterIssuer }}
    kind: ClusterIssuer
---
{{- end }}
{{- end }}
{{- end }}
