{{- $fullName := include "chart.fullname" . -}}
{{- if .Values.ingressRoute.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ $fullName }}-secured
spec:
  chain:
    middlewares:
    - name: {{ $fullName }}-hsts-headers
    {{- if .Values.ingressRoute.ipAllowList }}
    - name: {{ $fullName }}-known-ips
    {{- end }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ $fullName }}-https-only
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ $fullName }}-hsts-headers
spec:
  headers:
    forceSTSHeader: true
    stsIncludeSubdomains: false
    stsPreload: false
    stsSeconds: 315360000
---
{{- if .Values.ingressRoute.ipAllowList }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ $fullName }}-known-ips
spec:
  ipWhiteList:
    sourceRange:
    {{- range .Values.ingressRoute.ipAllowList }}
    - {{ . }}
    {{- end }}
{{- end }}
{{- end }}
