traefik:
  additionalArguments:
  - "--ping"
  - "--ping.entrypoint=traefik"
  - "--log.level=DEBUG"
  deployment:
    kind: DaemonSet
  service:
    enabled: false
  persistence:
    enabled: false
  hostNetwork: true
  securityContext:
    capabilities:
      add:
        - NET_BIND_SERVICE
    runAsNonRoot: false
    runAsUser: 0
  ports:
    web:
      port: 80
      expose: true
      protocol: TCP
      exposePort: 80
    websecure:
      port: 443
      expose: true
      protocol: TCP
      exposePort: 443
    traefik:
      port: 9000
      expose: true
      protocol: TCP
      exposePort: 9000
    metrics:
      port: 9050
      expose: true
      protocol: TCP
      exposePort: 9050
  tlsOptions:
    default:
      maxVersion: VersionTLS13
      minVersion: VersionTLS12
      cipherSuites:
      - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
      - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
      - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
      - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
      - "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305"
      - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"      
    maxtls12:
      maxVersion: VersionTLS12

cert-manager:
  installCRDs: true


global:
  image:
    pullPolicy: IfNotPresent
#    tag: $GITHUB_RUN_ID
  sharedContainerEnvVars:
    - name: TEST_SHARED
      value: "SHARED"