name: Building and deploying the test helm charts.
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
      - develop

jobs:
  call-workflow-staging-deploy:
    if: github.ref == 'refs/heads/develop'
    uses: ./.github/workflows/helm-deploy.yaml
    with:
      releaseEnv: staging
      chartName: testing-chart
    secrets: inherit

  call-workflow-production-deploy:
    if: github.ref == 'refs/heads/main'
    needs:
      - call-workflow-staging-deploy
    uses: ./.github/workflows/helm-deploy.yaml
    with:
      releaseEnv: production
      chartName: testing-chart
    secrets: inherit