name: Helm Deploy
on:
  workflow_call:
    secrets:
      KUBECONFIG:
        description: The Environment secret for KUBECONFIG
        required: true
    inputs:
      releaseEnv:
        required: true
        type: string
        default: "staging"

jobs:
  helm-deploy:
    runs-on: 'ubuntu-latest'
    environment:
      name: ${{ inputs.releaseEnv }}
    steps:
      - uses: actions/checkout@v2
      
      # - name: Create kubeconfig file
      #   run: |
      #     mkdir ${HOME}/.kube
      #     echo ${{ secrets.KUBECONFIG }} | base64 --decode > ${HOME}/.kube/config
      #     cat ${HOME}/.kube/config
      
      # - name: Set current context
      #   run: kubectl config use-context test-${{ inputs.releaseEnv }}
      
      - name: Headout Helm Action
        uses: headout/helm@v1.7.4
        
        run: |
          echo ${{ secrets.KUBECONFIG }}
          echo ./kubeconfig.yml
        with:
          release: 'test-$GITHUB_REF_NAME'
          namespace: '${{ inputs.releaseEnv }}'
          chart: 'testing-chart'
          token: '${{ github.token }}'
          helm: helm3
          values: |
            global:
              image:
                tag: $GITHUB_RUN_ID
          value-files: >-
            [
              "./testing-chart/values.yaml", 
              "./testing-chart/values-${{ inputs.releaseEnv }}.yaml"
            ]
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
