name: Helm Deploy
on:
  workflow_call:
    secrets:
      KUBECONFIG:
        description: The Environment secret for KUBECONFIG
        required: true
    inputs:
      releaseEnv:
        required: true
        type: string
        default: "staging"

jobs:
  helm-deploy:
    runs-on: 'ubuntu-latest'
    environment:
      name: ${{ inputs.releaseEnv }}
    steps:
      - uses: actions/checkout@v1

      - name: Headout Helm Action
        uses: headout/helm@v1.7.4
        
        with:
          release: 'test-$GITHUB_REF_NAME'
          namespace: '${{ inputs.releaseEnv }}'
          chart: 'testing-chart'
          token: '${{ github.token }}'
          values: |
            global:
              image:
                tag: $GITHUB_RUN_ID
          value-files: >-
            [
              "./testing-chart/values.yaml", 
              "./testing-chart/values-${{ inputs.releaseEnv }}.yaml"
            ]
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
